#ifndef GENETIC_ALGORITHM_CROSSOVERTYPE_H
#define GENETIC_ALGORITHM_CROSSOVERTYPE_H


enum class CrossoverType {
    PARTIALLY_MAPPED_CROSSOVER,
    ORDERED_CROSSOVER,
};

#endif //GENETIC_ALGORITHM_CROSSOVERTYPE_H
