#ifndef GENETIC_ALGORITHM_MUTATIONTYPE_H
#define GENETIC_ALGORITHM_MUTATIONTYPE_H

enum class MutationType {
    DISPLACEMENT_MUTATION,
    SCRAMBLE_MUTATION,
};

#endif //GENETIC_ALGORITHM_MUTATIONTYPE_H
